name: FTP Test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Test deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files
        uses: ./
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          ftp-remote-dir: /
          build-dir: ./
          exclusions: .git