name: FTP Test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Test deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files
        uses: ./
        with:
          server: ftptest.edwardcode.net
          username: ftptest
          password: ${{ secrets.ftp_password }}